#!/bin/sh
# make-paste-bundle.sh  --  LingTeX-Word
#
# Generates paste-ready copies of the VBA modules in build/paste/.
#
# Why this exists: pasting an exported .bas or .cls straight into the VBA editor
# does NOT work, and the reasons are not obvious.
#
#   * "Attribute VB_Name = ..." is read by the importer. Typed into the editor it
#     is a compile error.
#   * A .cls file carries a VERSION / BEGIN / MultiUse / END preamble and
#     VB_Creatable / VB_Exposed / VB_PredeclaredId attributes, none of which are
#     valid source.
#   * clsAppEvents has "Attribute mApp.VB_VarHelpID = -1" buried in the middle of
#     the file, which is easy to miss and also invalid when typed.
#
# This strips all of that and prepends a header saying the exact module name to
# set and whether to insert a standard module or a Class Module.
#
# PREFER IMPORTING. If your VBA editor offers File > Import File..., use the
# files in src/ directly and ignore this script -- importing needs no stripping
# and cannot go subtly wrong. This bundle is the fallback.
#
# POSIX sh, and no sed -i, so it behaves identically on macOS and Linux.
#
# Usage:  sh LingTeX-Word/tools/make-paste-bundle.sh

set -e

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
src="$root/src"
probe="$root/tools/probe"
out="$root/build/paste"

# Stage 1 first: these six reference nothing defined in the other seven, so they
# compile and run RunAllTests on their own, with the Word object model entirely
# uninvolved. See QUICKSTART.md.
STAGE1="modFlexParse modIgtModel modLeipzig modWrap clsIgtWarning modTests"
STAGE2="modStyles modSettings modMeasure modRender modReadBack modLingTeX clsAppEvents"

rm -rf "$out"
mkdir -p "$out"

# Resolve a module name to its source file, whichever extension it uses.
find_source() {
    if [ -f "$src/$1.bas" ]; then
        echo "$src/$1.bas"
    elif [ -f "$src/$1.cls" ]; then
        echo "$src/$1.cls"
    elif [ -f "$probe/$1.bas" ]; then
        echo "$probe/$1.bas"
    else
        echo ""
    fi
}

kind_of() {
    case "$1" in
        cls*) echo "Class Module" ;;
        *)    echo "Module" ;;
    esac
}

# Strip everything that is metadata rather than source, and any leading blanks,
# so the output begins at Option Explicit.
strip_metadata() {
    awk '
        /^VERSION [0-9]/           { next }
        /^BEGIN[ \t]*$/            { inpre = 1; next }
        /^END[ \t]*$/              { if (inpre) { inpre = 0; next } }
        inpre                      { next }
        /^Attribute[ \t]/          { next }
        !started && /^[ \t]*$/     { next }
        { started = 1; print }
    ' "$1"
}

emit() {
    name="$1"
    num="$2"
    stage="$3"
    file=$(find_source "$name")
    if [ -z "$file" ]; then
        echo "  MISSING: $name" >&2
        return 1
    fi
    kind=$(kind_of "$name")
    target="$out/$num-$name.txt"

    {
        echo "'============================================================="
        echo "' PASTE THIS INTO:  Insert > $kind"
        echo "' THEN SET ITS NAME TO:  $name"
        echo "'   (Properties pane, the (Name) row. On Mac: View > Properties"
        echo "'    Window if it is not already showing.)"
        echo "'"
        echo "' $stage"
        echo "'"
        echo "' Generated by tools/make-paste-bundle.sh from"
        echo "'   $(basename "$file")"
        echo "' Do not edit this file -- edit the original in src/ and re-run."
        echo "'============================================================="
        echo ""
        strip_metadata "$file"
    } > "$target"

    echo "  $num-$name.txt   ($kind)"
}

echo "Generating paste bundle in $out"
echo ""

emit modProbe 00 "Standalone probe. Run ProbeWord first, before anything else."

n=1
for m in $STAGE1; do
    num=$(printf "%02d" "$n")
    emit "$m" "$num" "STAGE 1 of 2 -- these six run RunAllTests on their own."
    n=$((n + 1))
done
for m in $STAGE2; do
    num=$(printf "%02d" "$n")
    emit "$m" "$num" "STAGE 2 of 2 -- adds the document work."
    n=$((n + 1))
done

cat > "$out/00-README.txt" <<'TXT'
LingTeX-Word -- paste bundle
============================

These are the VBA modules with their metadata stripped so they can be pasted
directly into the VBA editor. For each file:

  1. Insert > Module   (or Insert > Class Module for the cls* files -- the
     header of each file says which)
  2. Paste the whole file
  3. Set the module's name in the Properties pane to the name the header gives

Names matter. The code refers to the class modules by name, and a class pasted
into a standard module will not compile at all: clsAppEvents declares
"Private WithEvents mApp As Word.Application", which is only legal in a class
module.

IF YOUR EDITOR HAS File > Import File... USE THAT INSTEAD, on the files in
src/. It needs no stripping, sets the names for you, and cannot go subtly wrong.

Order to add them
-----------------

  00-modProbe              Run ProbeWord FIRST and send the output back. It
                           checks the Word features everything else depends on.

  Stage 1 -- no Word document is touched. Proves the parsing, projection,
  invariant and wrap-planning logic inside real Word VBA.

  01-modFlexParse
  02-modIgtModel
  03-modLeipzig
  04-modWrap
  05-clsIgtWarning         Class Module
  06-modTests

  Then, in the Immediate window (View > Immediate Window):   RunAllTests
  Expect every line to read PASS and the last line to read ALL PASS.

  Stage 2 -- adds everything that touches a document.

  07-modStyles
  08-modSettings
  09-modMeasure
  10-modRender
  11-modReadBack
  12-modLingTeX
  13-clsAppEvents          Class Module

  Then run AutoExec once, and see QUICKSTART.md for what to test.

VBA compiles the whole project at once, so stage 1 only works because those six
modules reference nothing defined in the other seven. That is checked
mechanically -- see the verification notes in QUICKSTART.md.
TXT

echo ""
echo "  00-README.txt    (read this first)"
echo ""
echo "Done. $(ls -1 "$out" | wc -l | tr -d ' ') files in $out"
